
services:
  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./alerts/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    restart: always
    depends_on:
      - prometheus
    networks:
      - observability

networks:
  observability:
    driver: bridge
