server:
  port: 7000
  error:
    include-message: always

waltid:
  issuer:
    credentials:
      - id: robskytecEmploymentVC
        name: Robskytec Employment Credential
        description: Verifiable credential for employment issued by Robskytec Limited
        template: robskytec-employment-template.json
        issuerDid: did:key:z6MkexampleCustomIssuerKey
        credentialSchema: https://example.com/schemas/robskytec-employment-schema.json
        persistIssuedCredentials: true
        vcsEndpointEnabled: true
